name: mytask_project
description: TaskMaster - A production-ready to-do list app with MVVM architecture.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.1.0
  firebase_messaging: ^15.2.0
  timezone: ^0.9.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  uuid: ^4.0.0

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_slidable: ^4.0.3
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
